# Generated by Django 5.0.6 on 2024-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_categorymodels_remove_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodels',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
