# Generated by Django 5.0.6 on 2024-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
