# Generated by Django 5.0.6 on 2024-06-15 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogmodel_image_blogcommentmodel'),
        ('users', '0005_remove_accountmodel_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='media_url',
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogmodel', verbose_name='blogs'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='users.teammodel', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogcategorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='blog-images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_info',
            field=models.TextField(null=True, verbose_name='short_info'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blogs.blogtagmodel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogtagmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
